### ISSUE TITLE
Error creating workflows in 3.6.2 release (currently latest) and 3.6.0 of Argo Workflows

### ISSUE THREAD

**Issue by malgnuz** [argoproj-labs/training-material#71]
Due to this regression bug [1] in Argo Workflows, using the current latest release (3.6.2) won't allow the creation of workflows successfully. This also affects release 3.6.0.

```
$ k get workflows -n argo
NAME    STATUS   AGE   MESSAGE
hello   Error    68s   Error (exit code 64): workflowtaskresults.argoproj.io is forbidden: User "system:serviceaccount:argo:argo" cannot create resource "workflowtaskresults" in API group "argoproj.io" in the namespace "argo"
```

Suggest using 3.5.X release of Argo Workflows until the bug is solved.

[1] https://github.com/argoproj/argo-workflows/issues/13341

**Comment by malgnuz** [comment]
Created this [PR](https://[github.com/argoproj-labs/training-material/pull/72](https://github.com/argoproj-labs/training-material/pull/72)) to highlight the issue in the Scenario documentation.

**Comment by abdesslem** [comment]
I got the same issue with the latest version, I solved it by granting privileges to argo user.

**Comment by tico24** [comment]
Upstream's 13341 is specifically related to the controller not being able to run http templates, which is not part of the scenarios in this training course.

The correct fix here is to teach the user that they should create a serviceaccount with these permissions and then use that serviceaccount in the workflow they run. I will add this today. https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/

**Comment by tico24** [comment]
So I have pushed fixes today to address the fact that the scenarios don't educate users on rbac requirements for running workflows.

I ran through all the scenarios with 3.6.2 and they all now run fine.

**Comment by abdesslem** [comment]
Thank you !

------------------------------

The preceding message (including attachments) is covered by the Electronic
Communication Privacy Act, 18 U.S.C. sections 2510-2512, is intended only
for the person or entity to which it is addressed, and may contain
information that is confidential, protected by attorney-client or other
privilege, or otherwise protected from disclosure by law. If you are not
the intended recipient, you are hereby notified that any retention,
dissemination, distribution, or copying of this communication is strictly
prohibited. Please reply to the sender that you have received the message
in error and destroy the original message and all copies.

_______________________________________________


Le jeu. 19 déc. 2024 à 09:56, Tim Collins ***@***.***> a
écrit :
